SELECT F.PASSENGER_KEY , P.PASSENGER_FIRSTNAME, P.PASSENGER_LASTNAME, P.PASSENGER_NATIONALITY, PP.LIFETIME_MILEAGE_TIER , SUM(f.Miles_Earned) AS Total_Miles_Earned,  SUM(f.Miles_Flown) AS Total_Miles_Flown, 
    RANK() over (ORDER BY SUM(f.Miles_Flown) DESC) AS Rank_Flyer
FROM Frequent_Flyer_Fact f
JOIN  Passenger_Dim p on F.PASSENGER_KEY = P.PASSENGER_KEY
JOIN  Passenger_Profile_Dim PP on F.PASSENGER_PROFILE_KEY = PP.PASSENGER_PROFILE_KEY
GROUP BY F.PASSENGER_KEY , P.PASSENGER_FIRSTNAME, P.PASSENGER_LASTNAME, P.PASSENGER_NATIONALITY, PP.LIFETIME_MILEAGE_TIER;



SELECT H.Passenger_Key, BC.CHANNEL_DESCRIPTION ,
       SUM(Number_of_Nights) AS Total_Nights_Spent
FROM Hotel_Fact H
JOIN Booking_Channel_Dim BC ON H.RESERVATION_CHANNEL_KEY = BC.CHANNEL_KEY
GROUP BY H.Passenger_Key, BC.CHANNEL_DESCRIPTION;



SELECT BC.CHANNEL_DESCRIPTION, Count(BC.CHANNEL_DESCRIPTION) Reservation_Count
FROM Hotel_Fact H
JOIN Booking_Channel_Dim BC ON H.RESERVATION_CHANNEL_KEY = BC.CHANNEL_KEY
GROUP BY BC.CHANNEL_DESCRIPTION
order by Reservation_Count desc;




SELECT C.Problem_Severity, I.TYPE,
       COUNT(*) AS Interaction_Count
FROM Customer_Care_Fact C
JOIN Interaction_Dim I on C.INTERACTION_KEY = I.INTERACTION_KEY
GROUP BY C.Problem_Severity, I.TYPE
ORDER BY Interaction_Count DESC;



SELECT count(FA.PASSENGER_KEY) Flight_Count , AR.AIRPORT_NAME AS Departure_Airport, A.AIRPORT_NAME AS Destination_Airport
FROM Flight_Activity_Fact FA
JOIN Airport_Dim AR on FA.DEPARTURE_AIRPORT_KEY = AR.AIRPORT_KEY
JOIN Airport_Dim A on FA.DESTINATION_AIRPORT_KEY = A.AIRPORT_KEY
GROUP BY AR.AIRPORT_NAME, A.AIRPORT_NAME
ORDER BY Flight_Count DESC;




SELECT SUM(FA.BASE_FARE_REVENUE) as Total_Revenue, PP.FREQUENT_FLYER_TIER, AR.AIRCRAFT_TYPE, AP.COUNTRY, AP.CITY
FROM Flight_Activity_Fact FA
JOIN Passenger_Profile_Dim PP on FA.PASSENGER_PROFILE_KEY = PP.PASSENGER_PROFILE_KEY
JOIN Aircraft_Dim AR on FA.AIRCRAFT_KEY = AR.AIRCRAFT_KEY
JOIN Airport_Dim AP on FA.DESTINATION_AIRPORT_KEY = AP.AIRPORT_KEY
GROUP BY PP.FREQUENT_FLYER_TIER, AR.AIRCRAFT_TYPE, AP.COUNTRY, AP.CITY
ORDER BY Total_Revenue DESC;



