INSERT INTO Interaction_Dim (Interaction_Key, Type, Description) VALUES (1, 'Phone Call', 'Initial contact with customer via phone call');
INSERT INTO Interaction_Dim (Interaction_Key, Type, Description) VALUES (2, 'Email', 'Follow-up email regarding inquiry');
INSERT INTO Interaction_Dim (Interaction_Key, Type, Description) VALUES (3, 'Support Ticket', 'Customer support ticket raised for support');
INSERT INTO Interaction_Dim (Interaction_Key, Type, Description) VALUES (4, 'In Person', 'Face-to-face Interaction_Dim with the client');