INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (1, 'Mastercard');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (2, 'Visa');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (3, 'Cash');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (4, 'PayPal');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (5, 'Bank Transfer');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (6, 'Mobile Wallet');
INSERT INTO Payment_Method_Dim (Payment_Method_Key, Payment_Type) VALUES (7, 'Miles Earned');

