-- No Class Change
INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (1, 'A', 'First Class', 'First Class', 'First Class-First Class', 'No Class Change');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (2, 'B', 'Business Class', 'Business Class', 'Business Class-Business Class', 'No Class Change');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (3, 'C', 'Premium Economy', 'Premium Economy', 'Premium Economy-Premium Economy', 'No Class Change');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (4, 'D', 'Economy Class', 'Economy Class', 'Economy Class-Economy Class', 'No Class Change');

-- Upgrade
INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (5, 'E', 'Economy Class', 'Business Class', 'Economy Class-Business Class', 'Upgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (6, 'F', 'Economy Class', 'First Class', 'Economy Class-First Class', 'Upgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (7, 'G', 'Premium Economy', 'First Class', 'Premium Economy-First Class', 'Upgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (8, 'H', 'Premium Economy', 'Business Class', 'Premium Economy-Business Class', 'Upgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (9, 'I', 'Economy Class', 'Premium Economy', 'Economy Class-Premium Economy', 'Upgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (10, 'J', 'First Class', 'Business Economy', 'First Class-Premium Economy', 'Upgrade');
-- Downgrade
INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (11, 'K', 'Business Class', 'First Class', 'Business Class-First Class', 'Downgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (12, 'L', 'First Class', 'Economy Class', 'First Class-Economy Class', 'Downgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (13, 'N', 'First Class', 'Premium Economy', 'First Class-Premium Economy', 'Downgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (14, 'O', 'Business Class', 'Premium Economy', 'Business Class-Premium Economy', 'Downgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (15, 'P', 'Business Class', 'Economy Class', 'Business Class-Economy Class', 'Downgrade');

INSERT INTO Class_of_Service_Flown (Class_of_Service_Key, Class_ID, Class_Purchased, Class_Flown, Purchased_Flown_Group, Class_Change_Indicator) VALUES (16, 'Q', 'Premium Economy', 'Economy Class', 'Premium Economy-Economy Class', 'Downgrade');
